# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wrapAmSolve <- function(X, y, initCf, constraints, lambdaTermFreq, lambdaTermDim, startIndex, maxIter, maxIterOptim, tol = 0.001, shouldCollectProgress = FALSE, startLambda = 0.1, shouldAccumulH = TRUE) {
    .Call('_papss_wrapAmSolve', PACKAGE = 'papss', X, y, initCf, constraints, lambdaTermFreq, lambdaTermDim, startIndex, maxIter, maxIterOptim, tol, shouldCollectProgress, startLambda, shouldAccumulH)
}

